spring:
  application:
    name: payment-service
  profiles:
    active: mocktest
  config:
    import: "optional:configserver:http://localhost:8888"

toss:
  payment:
    base-url: https://api.tosspayments.com
    secret-key: ${TOSS_SECRET_KEY}
    client-key: ${TOSS_CLIENT_KEY}
    customer-key: ${TOSS_CUSTOMER_KEY}
  mock:
    slow-rate: 0.05
    failure-rate: 0.03

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, prometheus