spring:
  application:
    name: payment-service

  profiles:
    active: mocktest

  config:
    import: "optional:configserver:http://localhost:8888"

  datasource:
    url: jdbc:postgresql://localhost:15432/trusta_market
    username: trusta_admin
    password: trusta_admin_pw
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: p_payment
        format_sql: true
    show-sql: true

  liquibase:
    default-schema: p_payment
    liquibase-schema: p_payment

eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

toss:
  payment:
    base-url: https://api.tosspayments.com
    secret-key: "test_sk_ORzdMaqN3w2AvAn6y9yY85AkYXQG"
    client-key: "test_ck_EP59LybZ8BDo7yajD4LYV6GYo7pR"
    customer-key: "aFNXGirOcx1ZjKalfy5K_"
  mock:
    slow-rate: 0.05
    failure-rate: 0.01

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, prometheus

trusta:
  swagger:
    expose-public: ${TRUSTA_SWAGGER_EXPOSE_PUBLIC:true}
  security:
    trust-gateway-headers: true

notification:
  discord:
    webhook-url: "https://discordapp.com/api/webhooks/1509821798991007806/sqIE3CMg2APRiav15F4mRYVHsVy7N_bioDCxxEmMZh4ORZeOKmbEQZLwBWl5JjY7EAsT"